site_name: Age of Empires II Random Map Script Reference
nav:
    - 0. Introduction: index.md
    - 1. Language Reference: 1_language_reference.md
    - 2. Terrains & Objects: 2_terrains_and_objects.md
    - 3. Testing: 3_testing.md
    - 4. Example Script: 4_example_script.md
    - 5. Links and Resources: 5_links_and_resources.md

theme: 
    name: readthedocs
    highlightjs: false # we use our own version
extra_javascript: [highlight.js, highlight.js-rms.js]
extra_css: [github.css]
docs_dir: 'source'
site_dir: 'docs'

